[build]
  command = "npm run build"  # Comando para construir tu sitio
  publish = "dist"           # Carpeta que contiene los archivos para desplegar

[context.production.environment]
  # Variables de entorno específicas para el entorno de producción
  NODE_ENV = "production"
  API_URL = "https://api.example.com"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/nosotros/*"
  to = "/nosotros.html"
  status = 200
  force = true

[[redirects]]
  from = "/publicaciones/*"
  to = "/publicaciones.html"
  status = 200
  force = true

  [[redirects]]
  from = "/videos/*"
  to = "/videos.html"
  status = 200
  force = true

  [[redirects]]
  from = "/proyectos/*"
  to = "/publicaciones.html"
  status = 200
  force = true
